# Generated by Django 5.1.3 on 2025-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprocessmodel',
            name='activeIcon',
            field=models.ImageField(default='media/images', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='workprocessmodel',
            name='inactiveIcon',
            field=models.ImageField(default='media/images', upload_to='images/'),
        ),
    ]
