# Generated by Django 5.1.3 on 2025-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_workprocessmodel_activeicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprocessmodel',
            name='activeIcon',
            field=models.FileField(default='media/images', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='workprocessmodel',
            name='inactiveIcon',
            field=models.FileField(default='media/images', upload_to='images/'),
        ),
    ]
