# Generated by Django 5.1.3 on 2025-04-07 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_workprocessmodel_activeicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
            ],
        ),
    ]
