# Generated by Django 5.1.3 on 2025-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_hometestimonialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('prof', models.CharField(max_length=50)),
                ('fburl', models.URLField(max_length=300)),
                ('instaurl', models.URLField(max_length=300)),
                ('twitterurl', models.URLField(max_length=300)),
                ('linkdinurl', models.URLField(max_length=300)),
            ],
        ),
    ]
