# Generated by Django 5.1.3 on 2025-04-10 08:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_teammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortdesc', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbimg', models.FileField(blank=True, null=True, upload_to='services/thumbs/')),
                ('redirecticon', models.FileField(blank=True, null=True, upload_to='services/icons/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SingleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('featuredimg', models.ImageField(blank=True, null=True, upload_to='singleservice/featured/')),
                ('moreimg', models.ImageField(blank=True, null=True, upload_to='singleservice/more/')),
                ('fulldesc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featureone', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featuretwo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('process', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pricing', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('processicon1', models.FileField(blank=True, null=True, upload_to='singleservice/process/')),
                ('processicon2', models.FileField(blank=True, null=True, upload_to='singleservice/process/')),
                ('processicon3', models.FileField(blank=True, null=True, upload_to='singleservice/process/')),
                ('moretext', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='backend.services')),
            ],
        ),
    ]
